apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-hosd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-hosd
    app.kubernetes.io/part-of: dc-metro-map-1
  name: dc-metro-map-hosd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: dc-metro-map-hosd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dc-metro-map-hosd
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/karthik-jk-tenant/dc-metro-map-1/dc-metro-map-hosd@sha256:d052558df5ea6630ec81958b90d112cba671d81124d1f4a593ab111bc096c586
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
