apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-hosd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-hosd
    app.kubernetes.io/part-of: dc-metro-map-1
  name: dc-metro-map-hosd
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: dc-metro-map-hosd
status:
  loadBalancer: {}
