apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-hosd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/karthik-jk-tenant/dc-metro-map-1/dc-metro-map-hosd@sha256:befb2b3b17b6038660cffc5e5d3132444707ba14c60475d7ebc6706810bfa82a
        name: container-image
        resources: {}
status: {}
